---
abstract: 'The great new AnyEvent::Worker!'
author:
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::If: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Worker
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent: 5
  Storable: 0
  common::sense: 2
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
